// Regenerate docs/TOOLS.md and docs/tools.json from the tool registry: node scripts/generate-tool-docs.ts
// (npm run docs:tools). docs/tools.json holds the tool counts and names per group; the website builder
// (python/src/sws_tools/website) reads it, since Python cannot import the TypeScript registry.
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as z from 'zod';
import { ALL_TOOLS } from '../src/tools/index.ts';
import { TOOL_GROUPS } from '../src/tools/types.ts';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const GROUP_INFO: Record<string, string> = {
  core: 'Navigate, read the page, interact, wait and take screenshots. Enough for most tasks.',
  content: 'Token-efficient reading and structured extraction.',
  forms: 'Understand and fill whole forms in one call.',
  tabs: 'Multiple tabs (all tabs share cookies).',
  state: 'Cookies and saved sessions (skip logins).',
  debug: 'Run JavaScript, read console output and network activity.',
  capture: 'PDF export and viewport size.',
  agents: 'Hand whole jobs to sub-agents with their own isolated browser (needs a model: config/models.json or AGENT_LLM_URL). See [AGENTS.md](AGENTS.md).',
  scripts: 'Stored automation scripts made by agent_automate: list, inspect, run (no model needed) and delete.',
  snapshots: 'Saved sign-ins (cookies and site storage for chosen sites; not page snapshots): list, save, describe, load and delete them. agent_run starts a sub-agent with one. See [SNAPSHOTS.md](SNAPSHOTS.md).',
};

/** HTML tag names in descriptions (<select>, <form>) as code, so Markdown renderers do not treat them as HTML. */
const md = (s: string) => s.replace(/<\/?[a-zA-Z][\w-]*>/g, (t) => `\`${t}\``);

function typeOf(schema: any): string {
  if (!schema) return 'any';
  if (schema.enum) return schema.enum.map((v: unknown) => JSON.stringify(v)).join(' \\| ');
  if (schema.type === 'array') return `${typeOf(schema.items)}[]`;
  if (schema.anyOf) return schema.anyOf.map(typeOf).join(' \\| ');
  if (schema.type === 'integer') return 'integer';
  return String(schema.type ?? 'object');
}

const lines: string[] = [
  '# Tool reference',
  '',
  '<!-- Generated by scripts/generate-tool-docs.ts. Do not edit by hand. -->',
  '',
  `The server exposes ${ALL_TOOLS.length} tools (the ${ALL_TOOLS.filter((t) => t.group === 'agents').length} \`agents\` tools only when a model is configured in [config/models.json](MODELS.md) or with AGENT_LLM_URL). Limit them with \`TOOLSETS\` (for example \`TOOLSETS=core,content\`), which helps small local models.`,
  '',
  '| Group | Tools | Purpose |',
  '|---|---|---|',
];
for (const g of TOOL_GROUPS) {
  const tools = ALL_TOOLS.filter((t) => t.group === g);
  if (!tools.length) continue;
  lines.push(`| \`${g}\` | ${tools.map((t) => `[\`${t.name}\`](#${t.name})`).join(', ')} | ${GROUP_INFO[g] ?? ''} |`);
}
lines.push('');

for (const g of TOOL_GROUPS) {
  const tools = ALL_TOOLS.filter((t) => t.group === g);
  if (!tools.length) continue;
  lines.push(`## Group \`${g}\``, '');
  for (const tool of tools) {
    const schema: any = z.toJSONSchema(tool.inputSchema);
    const props = Object.entries<any>(schema.properties ?? {});
    const required = new Set<string>(schema.required ?? []);
    lines.push(`### ${tool.name}`, '', `**${tool.title}**. ${md(tool.description)}`, '');
    const hints = [
      tool.annotations.readOnlyHint ? 'read-only' : 'changes page state',
      tool.annotations.openWorldHint ? 'interacts with websites' : 'local to the browser',
    ];
    lines.push(`_${hints.join(', ')}_`, '');
    if (props.length === 0) {
      lines.push('No parameters.', '');
    } else {
      lines.push('| Parameter | Type | Required | Description |', '|---|---|---|---|');
      for (const [name, p] of props) {
        const desc = md(String(p.description ?? '')).replace(/\|/g, '\\|');
        lines.push(`| \`${name}\` | ${typeOf(p)} | ${required.has(name) ? 'yes' : 'no'} | ${desc} |`);
      }
      lines.push('');
    }
  }
}

writeFileSync(path.join(ROOT, 'docs', 'TOOLS.md'), `${lines.join('\n').trimEnd()}\n`);

// every group in TOOL_GROUPS order (empty ones too), each with its tools in registry order
const manifest = {
  $comment: 'Generated by scripts/generate-tool-docs.ts (npm run docs:tools). Do not edit by hand.',
  total: ALL_TOOLS.length,
  browser: ALL_TOOLS.filter((t) => t.name.startsWith('browser_')).length,
  groups: Object.fromEntries(
    TOOL_GROUPS.map((g) => {
      const tools = ALL_TOOLS.filter((t) => t.group === g).map((t) => t.name);
      return [g, { count: tools.length, tools }];
    }),
  ),
};
writeFileSync(path.join(ROOT, 'docs', 'tools.json'), `${JSON.stringify(manifest, null, 2)}\n`);
console.log(`wrote docs/TOOLS.md and docs/tools.json (${ALL_TOOLS.length} tools)`);
